org: marinho12
service: async-process-image

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: us-east-1

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  create-live:
    handler: src/functions/http/create-live.handler
    events:
      - httpApi:
          path: /lives
          method: POST
