org: marinho12
service: async-process-image

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: us-east-1
  environment:
    LIVES_TABLE: !Ref LivesTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource: !GetAtt LivesTable.Arn

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  create-live:
    handler: src/functions/http/create-live.handler
    events:
      - httpApi:
          path: /lives
          method: POST

resources:
  Resources:
    LivesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LivesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
